"""CacheIndex protocol: stores entries and answers nearest-neighbor queries."""

from __future__ import annotations

from typing import Protocol

from semcache.models import CacheEntry


class CacheIndex(Protocol):
    def add(self, entry: CacheEntry) -> None: ...
    def get(self, key_hash: str) -> CacheEntry | None: ...
    def query(self, embedding: list[float], namespace: str) -> tuple[CacheEntry, float] | None: ...
    def remove(self, key_hash: str) -> None: ...
    def entries(self, namespace: str | None = None) -> list[CacheEntry]: ...
    def clear(self, namespace: str | None = None) -> None: ...
    def __len__(self) -> int: ...
